# Generated by Django 4.2.4 on 2023-09-01 22:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '__first__'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField(default=datetime.timezone)),
                ('status', models.CharField(choices=[('E', 'Entregue'), ('A', 'Alugado')], max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('livro', models.ManyToManyField(to='livros.livro')),
            ],
        ),
    ]
