# Generated by Django 4.2.4 on 2023-09-01 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 19, 48, 12, 937209)),
        ),
    ]
